### ISSUE TITLE
Null is not converted to None but to {'NULL': True}

### ISSUE THREAD

**Issue by HWiese1980** [Alonreznik/dynamodb-json#11]
Hi, 

I would expect a null value in the JSON code to be converted to `None` instead of `{"NULL": True}`.

Is there a reason for this conversion?

**Comment by HWiese1980** [comment]
Just saw that that's what's also written in the original DynamoDB JSON when a value is considered NULL. That explains it. I'll investigate further.

**Comment by HWiese1980** [comment]
It seems to be the way that "null/none" is usually stored in DynamoDB JSON. I'm however wondering why `dynamodb-json` does not seem to handle it well.

**Comment by Alonreznik** [comment]
Hi @HWiese1980 .
Sorry for the late response.
Can you describe what is not handle the Null value well in the repo?

**Comment by HWiese1980** [comment]
As I mentioned in the initial post, a value stored as  `{'NULL': True}` in DynamoDB was - at the time of opening this issue - not unmarshalled to `None`. I'm not sure to what it was unmarshalled. You can try it yourself. Marshall an object from normal JSON that contains a `None` somewhere into a DynamoDB JSON object. The `None` should be converted into `{'NULL': True}`. Then unmarshall it again and check what that `{'NULL': True}` is converted to.

**Comment by Alonreznik** [comment]
Hi @HWiese1980.
Thanks for reaching out! Appreciated.

I've made a quick check and it seems working as expected:

```
>>> from dynamodb_json import json_util
>>> json_util.dumps({"MyName": None})
'{"MyName": {"NULL": true}}'
>>> json_util.loads('{"MyName": {"NULL": true}}')
{'MyName': None}
```
