### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [Alonreznik/dynamodb-json#12]
Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'rdf4|tool|doc' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./dynamodb_json/json_util.py:63: DeprecationWarning: invalid escape sequence \d
  if re.match("^-?\d+?\.\d+?$", dct['N']) is not None:
```

**Comment by Alonreznik** [comment]
Hi @tirkarthi .
Thank you.

Will be fixed soon.

**Comment by einstein-aws** [comment]
Hi. Any update on this? Still getting this warning. Thanks!

**Comment by Alonreznik** [comment]
Fixed in https://github.com/Alonreznik/dynamodb-json/pull/25

**Comment by einstein-aws** [comment]
Thanks!
