### ISSUE TITLE
json.load() missing?

### ISSUE THREAD

**Issue by ShaunGriffithRyff** [Alonreznik/dynamodb-json#13]
I've just stumbled on this repo, so forgive me if I've not understood.

I'd like to replace all my json imports with this one. However, `json.load(filename)` is not available?

**Comment by Alonreznik** [comment]
Hi @ShaunGriffithRyff .
How are you?

This repo is just a util, that used for converting python dicts into the dynamodb format json. This is not meant to replace the json loads/dumps built-ins. The main goal here is connecting and using Dynamodb json formatting, which isn't straight-forward one and hard to maintain - so reading or writing files aren't included here.

In order of using reading file for example, you can read  using the object_hook in the util. 
Usage:  `json.load(file_obj, object_hook=dynamodb_json.object_hook)`
