### ISSUE TITLE
Empty string boto3 error.

### ISSUE THREAD

**Issue by mpbunch** [Alonreznik/dynamodb-json#3]
Does not seem to handle empty strings.
In:      {"desc":""}
Out:   {"desc":{"S":""}}

Error Message:
botocore.exceptions.ClientError:
An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty string

**Comment by Alonreznik** [comment]
Hello There!
Dynamodb cannot handle empty string as value. 
In order not to force that behavior of removing empty string or change an empty string to null by the generic library, that issue won't be fixed.

Sorry for that :)

Alon

**Comment by mpbunch** [comment]
Because dynamodb cant handle empty values, and this script is labeled "dynamodb-json". It would make sense that the script would force appropriate behavior; or at least provide a flag to enable the removal of empty values.  Otherwise, everyone who uses this script will need to modify it in order to ensure they are creating valid dynamodb-json.

**Comment by Alonreznik** [comment]
Sure. But this is just a tool that supposed to convert your python dict, or regular json, into a valid DynamoDB json. The library was not meant to be a replacement for validation of your data and can not be relied on for doing that!
However, I will add a flag for that case tough, so it can be passed for removing empty strings from your json.

Thanks

**Comment by benaneesh** [comment]
Hi was this ever done? If so whats the flag?

**Comment by Alonreznik** [comment]
Hi @benaneesh.
Haven't done yet. As mentioned before, this is just a tool that supposed to convert your python dict, or regular json, into a valid DynamoDB json. The library was not meant to be a replacement for validation of your data and can not be relied on for doing that.
