### ISSUE TITLE
Some of the fields did not load successfully

### ISSUE THREAD

**Issue by jinghuaz** [Alonreznik/dynamodb-json#8]
{
	"ipc": "C01B39/36",
	"description_en": ".. Pentasil type, e.g. types ZSM-5, ZSM-8 or ZSM-11 [2006.01]",
	"parent_en": ["C01B", "C01", "C", "C01B39/02", "C01B39/00"],
	"update_ts": 1528363424837,
	"version": "2018.01",
	"description_cn": {
		"S": "··Pentasil型，如ZSM-5、ZSM-8或ZSM-11型〔6〕"
	},
	"parent_cn": ["C01B", "C01", "C", "C01B39/02", "C01B39/00"]
}
![image](https://user-images.githubusercontent.com/9525903/42021212-9867d286-7aec-11e8-92fc-7b2246f6926c.png)

**Comment by jinghuaz** [comment]
I mean that "description_cn" field still have "S"
![image](https://user-images.githubusercontent.com/9525903/42021303-d90138d2-7aec-11e8-80d6-4b91d96b488c.png)

**Comment by jinghuaz** [comment]
and Binary type not can hanlder,can help optimize,thanks!

**Comment by Alonreznik** [comment]
Connected to 
https://github.com/Alonreznik/dynamodb-json/issues/10
